import type { Brand } from "@/types/game";

export const BRANDS: Brand[] = [
  {
    id: "bbq",
    real: "BBQ",
    meme: "삐삐큐",
    menu: "황끔올리뷔",
    color: "#8B4513",
    chickenColor: "#D4A017",
    description: "바삭한 황금빛 올리브 치킨",
    emoji: "🍗",
  },
  {
    id: "bhc",
    real: "BHC",
    meme: "삐에이취씨",
    menu: "뿌릉클",
    color: "#FF69B4",
    chickenColor: "#FFB6C1",
    description: "달콤한 핑크빛 크리스피",
    emoji: "🍖",
  },
  {
    id: "kyochon",
    real: "교촌",
    meme: "꾜촌",
    menu: "허늬콤보",
    color: "#C8102E",
    chickenColor: "#E8A87C",
    description: "꿀처럼 달콤한 간장 치킨",
    emoji: "🐔",
  },
  {
    id: "goobne",
    real: "굽네",
    meme: "꿉네",
    menu: "고츄바사사삭",
    color: "#FF4500",
    chickenColor: "#FF6347",
    description: "매콤하게 구운 바삭 치킨",
    emoji: "🐓",
  },
  {
    id: "nene",
    real: "네네",
    meme: "녜녜",
    menu: "오린엔탈파닭",
    color: "#9370DB",
    chickenColor: "#DDA0DD",
    description: "오리엔탈 소스의 파닭",
    emoji: "🐤",
  },
  {
    id: "pelicana",
    real: "페리카나",
    meme: "펠리카냐",
    menu: "양념치킹",
    color: "#FF8C00",
    chickenColor: "#FFA500",
    description: "양념의 클래식 원조 치킨",
    emoji: "🐥",
  },
  {
    id: "puradak",
    real: "푸라닭",
    meme: "뿌라닭",
    menu: "블랙알릭",
    color: "#2F4F4F",
    chickenColor: "#696969",
    description: "블랙 마늘의 깊은 풍미",
    emoji: "🥩",
  },
  {
    id: "hosigi",
    real: "호식이두마리치킨",
    meme: "홓식이",
    menu: "매운간장치킹",
    color: "#228B22",
    chickenColor: "#90EE90",
    description: "매운 간장의 한마리 치킨",
    emoji: "🐣",
  },
  {
    id: "mexicana",
    real: "멕시카나",
    meme: "맥시카냐",
    menu: "와삭칸",
    color: "#DAA520",
    chickenColor: "#F0E68C",
    description: "와삭하게 튀긴 정통 치킨",
    emoji: "🦃",
  },
  {
    id: "jicoba",
    real: "지코바",
    meme: "찌코바",
    menu: "양념치킹",
    color: "#DC143C",
    chickenColor: "#FF6B6B",
    description: "새빨간 양념의 매운맛",
    emoji: "🥚",
  },
  {
    id: "60gye",
    real: "60계치킨",
    meme: "육공계",
    menu: "크크크치킹",
    color: "#4169E1",
    chickenColor: "#87CEEB",
    description: "크리스피의 삼중 바삭함",
    emoji: "🪺",
  },
  {
    id: "kkanbu",
    real: "깐부치킨",
    meme: "깐부",
    menu: "깐부통닭",
    color: "#FFD700",
    chickenColor: "#FFEC8B",
    description: "통째로 한마리 깐부 치킨",
    emoji: "🦴",
  },
  {
    id: "jadam",
    real: "자담치킨",
    meme: "쟈담",
    menu: "맵슐랭",
    color: "#8B0000",
    chickenColor: "#CD5C5C",
    description: "미슐랭급 매운 치킨",
    emoji: "🍗",
  },
  {
    id: "norangtongdak",
    real: "노랑통닭",
    meme: "노랑똥닭",
    menu: "우도땅콩치킹",
    color: "#F4A460",
    chickenColor: "#DEB887",
    description: "우도 땅콩의 고소한 치킨",
    emoji: "🥜",
  },
  {
    id: "bodram",
    real: "보드람치킨",
    meme: "뽀드람",
    menu: "후라이듀",
    color: "#6B8E23",
    chickenColor: "#9ACD32",
    description: "보드랍게 튀긴 후라이드",
    emoji: "🐔",
  },
  {
    id: "toraeore",
    real: "또래오래",
    meme: "또래오랭",
    menu: "오곡후라이듀",
    color: "#B8860B",
    chickenColor: "#DAA520",
    description: "오곡으로 바삭하게 튀긴 치킨",
    emoji: "🌾",
  },
];

/** 브랜드 ID로 찾기 */
export function getBrand(id: string): Brand | undefined {
  return BRANDS.find((b) => b.id === id);
}

/** 브랜드별 평균 시중 가격 (원) - 정보 표시용 */
export const BRAND_PRICES: Record<string, number> = {
  bbq: 22000,
  bhc: 20000,
  kyochon: 21000,
  goobne: 20000,
  nene: 23000,
  pelicana: 23000,
  puradak: 21000,
  hosigi: 17500,
  mexicana: 21000,
  jicoba: 22500,
  "60gye": 21900,
  kkanbu: 19000,
  jadam: 23000,
  norangtongdak: 24000,
  bodram: 21000,
  toraeore: 19000,
};

/** 전체 평균 치킨 가격 */
export function getAverageChickenPrice(): number {
  const prices = Object.values(BRAND_PRICES);
  return Math.round(prices.reduce((a, b) => a + b, 0) / prices.length);
}
